default:
  image: maven:3-openjdk-11-slim

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

build:
  stage: build
  script:
    - mvn clean compile

test:
  stage: test
  script:
    - mvn test
