---
application:
  mock: false
arduino:
  port: /dev/ttyACM0
logging:
  file:
    name: smartgarden.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-file-size: 10MB
      max-history: 7
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
server:
  port: 8081
  shutdown: graceful
spring:
  application:
    name: "Smart Garden"
  boot:
    admin:
      client:
        url: "http://localhost:8081"
watering:
  cron: "30 0/30 * * * *"
  period: 5
