application:
  mock: true
arduino:
  port: /dev/ttyACM0
logging:
  file:
    name: smartgarden.log
    path: /opt/smartgarden/
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-history: 7
      max-file-size: 10MB
server:
  port: 8081
watering:
  cron: '30 0/30 * * * *'
  period: 5
  sensor:
    sensor1:
      port: 14
      # Wet
      low: 300
      # Dry
      high: 650
    sensor2:
      port: 15
      # Wet
      low: 300
      # Dry
      high: 650
    sensor3:
      port: 16
      # Wet
      low: 300
      # Dry
      high: 650
    sensor4:
      port: 17
      # Wet
      low: 300
      # Dry
      high: 650
