---
application:
  mock: false

arduino:
  port: /dev/ttyACM0

logging:
  file:
    name: ~/smartgarden.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-file-size: 10MB
      max-history: 7
  level:
    com:
      github:
        fwidder: DEBUG
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: "Smart Garden"
  datasource:
    url: jdbc:h2:file:~/smartgarden-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true

watering:
  # cron: "30 0/30 * * * *"
  cron: "0 */5 * * * *"
  period: 10
