INSERT INTO PUBLIC.SETTING (ID, NAME, VALUE) VALUES (1, 'PUMP_1', 'false');
INSERT INTO PUBLIC.SETTING (ID, NAME, VALUE) VALUES (2, 'PUMP_2', 'false');
INSERT INTO PUBLIC.SETTING (ID, NAME, VALUE) VALUES (3, 'PUMP_3', 'false');